name: Test
on: [push]
jobs:
  posix:
    strategy:
      matrix:
        os: [ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
      - run: pip3 install pyyaml
      - run: python3 test.py
  linux-i386:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          dpkg --add-architecture i386
          apt-get update
          apt-get install g++-i686-linux-gnu
      - uses: actions/setup-python@v5
        with:
          cache: pip
      - run: pip3 install pyyaml
      - run: python3 test.py --cross i386
  windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-yaml
            mingw-w64-x86_64-python-pywin32
      - run: python3 test.py
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ucrt64
          install: mingw-w64-ucrt-x86_64-gcc
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v5
        with:
          cache: pip
      - run: pip3 install pyyaml pywin32
      - run: python3 test.py --msvc
