name: Test
on: [push]
jobs:
  posix:
    strategy:
      matrix:
        os: [ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
      - run: pip3 install pyyaml
      - run: python3 test.py
  windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-python
      - run: pip3 install pyyaml
      - run: python3 test.py
